;// *** DO NOT EDIT THIS FILE ***
;// this is include file for ca65 with .o65 lunix target
;// use it only with current kernel - make LNG first to regenerate this file
;// -rw-r--r-- 1 steffen steffen 1122 Jun 21 10:22 kfunc_tab.s

.import LUNIXKERNEL

lkf_jumptab = LUNIXKERNEL
lkf_set_zpsize = lkf_jumptab + 0
lkf_get_moduleif = lkf_jumptab + 2
lkf_fopen = lkf_jumptab + 4
lkf_fopendir = lkf_jumptab + 6
lkf_fclose = lkf_jumptab + 8
lkf_fgetc = lkf_jumptab + 10
lkf_fputc = lkf_jumptab + 12
lkf_fcmd = lkf_jumptab + 14
lkf_freaddir = lkf_jumptab + 16
lkf_fgetdevice = lkf_jumptab + 18
lkf_strout = lkf_jumptab + 20
lkf_popen = lkf_jumptab + 22
lkf_ufd_open = lkf_jumptab + 24
lkf_fdup = lkf_jumptab + 26
lkf_print_error = lkf_jumptab + 28
lkf_suicerrout = lkf_jumptab + 30
lkf_suicide = lkf_jumptab + 32
lkf_palloc = lkf_jumptab + 34
lkf_free = lkf_jumptab + 36
lkf_force_taskswitch = lkf_jumptab + 38
lkf_forkto = lkf_jumptab + 40
lkf_getipid = lkf_jumptab + 42
lkf_signal = lkf_jumptab + 44
lkf_sendsignal = lkf_jumptab + 46
lkf_wait = lkf_jumptab + 48
lkf_sleep = lkf_jumptab + 50
lkf_lock = lkf_jumptab + 52
lkf_unlock = lkf_jumptab + 54
lkf_suspend = lkf_jumptab + 56
lkf_hook_alert = lkf_jumptab + 58
lkf_hook_irq = lkf_jumptab + 60
lkf_hook_nmi = lkf_jumptab + 62
lkf_panic = lkf_jumptab + 64
lkf_locktsw = lkf_jumptab + 66
lkf_unlocktsw = lkf_jumptab + 68
lkf_add_module = lkf_jumptab + 70
lkf_fix_module = lkf_jumptab + 72
lkf_mpalloc = lkf_jumptab + 74
lkf_spalloc = lkf_jumptab + 76
lkf_pfree = lkf_jumptab + 78
lkf_mun_block = lkf_jumptab + 80
lkf_catcherr = lkf_jumptab + 82
lkf_printk = lkf_jumptab + 84
lkf_hexout = lkf_jumptab + 86
lkf_disable_nmi = lkf_jumptab + 88
lkf_enable_nmi = lkf_jumptab + 90
lkf_get_bitadr = lkf_jumptab + 92
lkf_addtask = lkf_jumptab + 94
lkf_get_smbptr = lkf_jumptab + 96
lkf_smb_alloc = lkf_jumptab + 98
lkf_smb_free = lkf_jumptab + 100
lkf_alloc_pfd = lkf_jumptab + 102
lkf_io_return = lkf_jumptab + 104
lkf_io_return_error = lkf_jumptab + 106
lkf_ref_increment = lkf_jumptab + 108
lkf_p_insert = lkf_jumptab + 110
lkf_p_remove = lkf_jumptab + 112
lkf__raw_alloc = lkf_jumptab + 114
lkf_exe_reloc = lkf_jumptab + 116
lkf_exe_test = lkf_jumptab + 118
lkf_init = lkf_jumptab + 120
lkf_keyb_joy0 = lkf_jumptab + 122
lkf_keyb_joy1 = lkf_jumptab + 124
lkf_keyb_scan = lkf_jumptab + 126
lkf_keyb_stat = lkf_jumptab + 128
lkf_random = lkf_jumptab + 130
lkf_srandom = lkf_jumptab + 132
lkf_getenv = lkf_jumptab + 134
lkf_setenv = lkf_jumptab + 136
